import "dotenv/config";
import { PrismaClient } from "../src/generated/prisma/client.js";
import { PrismaPg } from "@prisma/adapter-pg";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

const products = [
  {
    name: "Modern Light",
    slug: "modern-light",
    subtitle: "Hanging Light",
    description: "A sleek modern pendant lamp with clean geometric lines. Crafted from premium brushed aluminum, this fixture casts a warm ambient glow perfect for dining areas and living rooms. Features adjustable cable length and a wide beam angle for versatile illumination.",
    category: "Pendant",
    style: "Modern",
    color: "Gold",
    material: "Aluminum",
    wattage: 40,
    voltage: "110-240V",
    dimmable: true,
    inStock: true,
    featured: true,
    image: "/modern-lamp.png",
    images: ["/modern-lamp.png"],
  },
  {
    name: "Industrial Light",
    slug: "industrial-light",
    subtitle: "Hanging Light",
    description: "An industrial-style pendant lamp inspired by vintage factory lighting. Features a robust iron frame with an exposed bulb design that adds raw character to any space. Perfect for lofts, kitchens, and creative workspaces.",
    category: "Pendant",
    style: "Industrial",
    color: "Black",
    material: "Iron",
    wattage: 60,
    voltage: "110-240V",
    dimmable: false,
    inStock: true,
    featured: true,
    image: "/industrial-lamp.png",
    images: ["/industrial-lamp.png"],
  },
  {
    name: "Superbolw Light",
    slug: "superbolw-light",
    subtitle: "Hanging Light",
    description: "A bold bowl-shaped pendant light with a curved silhouette. The inner reflective surface maximizes light output while the matte exterior adds sophistication. Ideal for kitchen islands and entryways.",
    category: "Pendant",
    style: "Contemporary",
    color: "White",
    material: "Ceramic",
    wattage: 45,
    voltage: "110-240V",
    dimmable: true,
    inStock: true,
    featured: false,
    image: "/superbolw-lamp.png",
    images: ["/superbolw-lamp.png"],
  },
  {
    name: "Ultrawide Light",
    slug: "ultrawide-light",
    subtitle: "Hanging Light",
    description: "An expansive wide-shade pendant that delivers broad, even illumination. The minimalist disc design floats elegantly above surfaces, making it a statement piece for modern dining rooms and conference tables.",
    category: "Pendant",
    style: "Minimalist",
    color: "Gold",
    material: "Brass",
    wattage: 50,
    voltage: "110-240V",
    dimmable: true,
    inStock: true,
    featured: true,
    image: "/ultrawide-lamp.png",
    images: ["/ultrawide-lamp.png"],
  },
  {
    name: "Roundness Light",
    slug: "roundness-light",
    subtitle: "Hanging Light",
    description: "A perfectly spherical globe pendant that diffuses light evenly in all directions. Hand-blown frosted glass creates a soft, inviting atmosphere. A timeless design suitable for bedrooms and reading nooks.",
    category: "Pendant",
    style: "Classic",
    color: "White",
    material: "Glass",
    wattage: 35,
    voltage: "110-240V",
    dimmable: true,
    inStock: true,
    featured: false,
    image: "/roundness-light.png",
    images: ["/roundness-light.png"],
  },
  {
    name: "Stickness Light",
    slug: "stickness-light",
    subtitle: "Hanging Light",
    description: "A striking stick-form chandelier with multiple vertical LED tubes. The clustered design creates a dramatic waterfall effect of light. Perfect as a centerpiece in high-ceiling spaces and stairwells.",
    category: "Chandelier",
    style: "Modern",
    color: "Gold",
    material: "Brass",
    wattage: 80,
    voltage: "110-240V",
    dimmable: true,
    inStock: true,
    featured: true,
    image: "/stickness-light.png",
    images: ["/stickness-light.png"],
  },
  {
    name: "Superjet Light",
    slug: "superjet-light",
    subtitle: "Hanging Light",
    description: "An aerodynamic pendant with a jet-inspired silhouette. The elongated form directs focused light downward while side vents cast ambient patterns on surrounding walls. A conversation starter for modern interiors.",
    category: "Pendant",
    style: "Futuristic",
    color: "Silver",
    material: "Aluminum",
    wattage: 55,
    voltage: "110-240V",
    dimmable: false,
    inStock: true,
    featured: false,
    image: "/superjet-light.png",
    images: ["/superjet-light.png"],
  },
  {
    name: "Nakedness Light",
    slug: "nakedness-light",
    subtitle: "Hanging Light",
    description: "A stripped-back exposed bulb pendant that celebrates simplicity. The minimal socket and woven cord let the filament bulb take center stage. Perfect for Scandinavian and bohemian-inspired spaces.",
    category: "Pendant",
    style: "Scandinavian",
    color: "Black",
    material: "Wood",
    wattage: 25,
    voltage: "110-240V",
    dimmable: false,
    inStock: true,
    featured: false,
    image: "/nakedness-lamp.png",
    images: ["/nakedness-lamp.png"],
  },
  {
    name: "Classic Light",
    slug: "classic-light",
    subtitle: "Hanging Light",
    description: "A timeless lantern-style pendant with traditional craftsmanship. Ornate metalwork frames clear glass panels, creating a warm heritage feel. Ideal for hallways, porches, and traditional dining rooms.",
    category: "Lantern",
    style: "Classic",
    color: "Bronze",
    material: "Iron",
    wattage: 40,
    voltage: "110-240V",
    dimmable: true,
    inStock: true,
    featured: false,
    image: "/modern-lamp.png",
    images: ["/modern-lamp.png"],
  },
  {
    name: "Elegant Light",
    slug: "elegant-light",
    subtitle: "Hanging Light",
    description: "A luxury crystal-accented pendant that combines modern engineering with classic elegance. Precision-cut crystal elements refract light into dazzling patterns across the room. The ultimate statement piece for formal spaces.",
    category: "Chandelier",
    style: "Luxury",
    color: "Gold",
    material: "Crystal",
    wattage: 75,
    voltage: "110-240V",
    dimmable: true,
    inStock: true,
    featured: true,
    image: "/industrial-lamp.png",
    images: ["/industrial-lamp.png"],
  },
  {
    name: "Orbit Light",
    slug: "orbit-light",
    subtitle: "Ceiling Light",
    description: "A sculptural ring pendant inspired by planetary orbits. The LED-integrated ring casts even, shadow-free illumination while the floating design adds architectural drama. Perfect for minimalist living spaces.",
    category: "Pendant",
    style: "Minimalist",
    color: "Gold",
    material: "Aluminum",
    wattage: 36,
    voltage: "110-240V",
    dimmable: true,
    inStock: true,
    featured: false,
    image: "/ultrawide-lamp.png",
    images: ["/ultrawide-lamp.png"],
  },
  {
    name: "Cascade Light",
    slug: "cascade-light",
    subtitle: "Chandelier",
    description: "A multi-tier cascading chandelier with hand-blown glass droplets. Each tier descends gracefully, creating a waterfall of warm light. Transforms high-ceiling rooms into grand, inviting spaces.",
    category: "Chandelier",
    style: "Contemporary",
    color: "Silver",
    material: "Glass",
    wattage: 100,
    voltage: "110-240V",
    dimmable: true,
    inStock: true,
    featured: true,
    image: "/superbolw-lamp.png",
    images: ["/superbolw-lamp.png"],
  },
  {
    name: "Zenith Light",
    slug: "zenith-light",
    subtitle: "Floor Lamp",
    description: "A tall arc floor lamp that sweeps gracefully over seating areas. The heavy marble base provides stability while the adjustable shade directs light precisely where needed. A functional sculpture for any room.",
    category: "Floor Lamp",
    style: "Modern",
    color: "Black",
    material: "Marble",
    wattage: 60,
    voltage: "110-240V",
    dimmable: true,
    inStock: true,
    featured: false,
    image: "/stickness-light.png",
    images: ["/stickness-light.png"],
  },
  {
    name: "Aurora Light",
    slug: "aurora-light",
    subtitle: "Table Lamp",
    description: "A stunning table lamp with a gradient-tinted glass shade that mimics the northern lights. The warm-to-cool color transition creates a mesmerizing ambient effect. Perfect for bedside tables and accent lighting.",
    category: "Table Lamp",
    style: "Contemporary",
    color: "Gold",
    material: "Glass",
    wattage: 25,
    voltage: "110-240V",
    dimmable: true,
    inStock: true,
    featured: false,
    image: "/roundness-light.png",
    images: ["/roundness-light.png"],
  },
  {
    name: "Prism Light",
    slug: "prism-light",
    subtitle: "Wall Sconce",
    description: "A geometric wall sconce that splits light into angular beams. The faceted metal shade creates dynamic shadow patterns on adjacent surfaces. An artistic addition to corridors and accent walls.",
    category: "Wall Sconce",
    style: "Industrial",
    color: "Bronze",
    material: "Iron",
    wattage: 30,
    voltage: "110-240V",
    dimmable: false,
    inStock: true,
    featured: false,
    image: "/superjet-light.png",
    images: ["/superjet-light.png"],
  },
  {
    name: "Nimbus Light",
    slug: "nimbus-light",
    subtitle: "Ceiling Light",
    description: "A cloud-like flush-mount ceiling light with organic curves. The layered fabric shade softens LED output to produce a soothing, diffused glow. Ideal for bedrooms, nurseries, and meditation spaces.",
    category: "Ceiling Light",
    style: "Scandinavian",
    color: "White",
    material: "Fabric",
    wattage: 30,
    voltage: "110-240V",
    dimmable: true,
    inStock: true,
    featured: false,
    image: "/nakedness-lamp.png",
    images: ["/nakedness-lamp.png"],
  },
];

async function main() {
  console.log("Seeding database...");
  for (const product of products) {
    await prisma.product.upsert({
      where: { slug: product.slug },
      update: product,
      create: product,
    });
  }
  console.log(`Seeded ${products.length} products.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
